### PR TITLE
ru.cfg

### PR DESCRIPTION
**Pull request by BenDJaminUt**
Russian Translation

### CODE REVIEW

**Comment by Nils277** [comment]
Thanks!

**Comment by Nils277** [comment]
Ehrm...the file seems to be completely in english, is this intended?

**Comment by BenDJaminUt** [comment]
I know, I didn't started yet, sorry

**Comment by BenDJaminUt** [comment]
What K&K means? xd

**Comment by Nils277** [comment]
Ah okay, no problem. Was just wondering 
You may want to contact [Dr. Jet](http://forum.kerbalspaceprogram.com/index.php?/profile/99880-dr-jet/) from the KSP forum. He is also currently working on a translation of KPBS into russian.

**Comment by Nils277** [comment]
Oh and K&K is the short version of *Kerman&Kerman*

**Comment by BenDJaminUt** [comment]
Thank you! :)

**Comment by BenDJaminUt** [comment]
Im a bit confused... how can i work with Dr.Jet together? >.<

**Comment by Tirathangil** [comment]
> I'm a bit confused... how can i work with Dr.Jet together? >.<
Just discuss who will translate the various parts.  If there is no text line conflicts in the lines, the merge will be ideal.
P.S. Just a my humble advice.

**Comment by BenDJaminUt** [comment]
Thank you again

**Comment by Tirathangil** [comment]
> Thank you again
No, no, тhere is nothing to thank, I just passed by. :)

**Comment by BenDJaminUt** [comment]
;D

**Comment by BenDJaminUt** [comment]
Sure! :D

**Comment by BenDJaminUt** [comment]
Looks like they said "no" ._.

**Comment by Nils277** [comment]
yeah, i'm sorry about that. Maybe you two could agree that one is doing the ingame translation and the other one does the KSPedia entries ;)

**Comment by Nils277** [comment]
Hmm well, KSPedia seems to have been translated too in the meantime.

**Comment by BenDJaminUt** [comment]
I can translate anything else ;D
Anyway it was good to talk with you

**Comment by Nils277** [comment]
Likewise :)
Will let you know when i have new parts or entries to translate!

**Comment by BenDJaminUt** [comment]
:D

**Pull request closed without merging**
