### PR TITLE
USI-LS Rebalance

### PR DESCRIPTION
**Pull request by DanStaal**
# Large MM Patch
- Greenhouse slightly less powerful in production, better in hab.  (And uses a lot less EC.)
-  Central Hub is no longer a base on it’s own.
    - Base hab replaced with Hab Multiplier
    - Recycler removed.
    - Purifier adjusted to be more powerful, with less capacity.
    - Resource storage removed.
-  Habitats given a small multiplier, at the cost of Base Hab
- Coupola tweaked.
- Science lab loses recycler, gains small hab multiplier.

# Algae Container
Complete relook at the Algae container - now has several modes, including the original, which has been tweaked.

Modes are:
- ‘Dry’: Mulch+Ore -> Fertilizer
- ‘Wet’: Water+Ore - > Mulch+Fertilizer
- Soylent Green
- Soylent Red

# Other
Rebalanced the Greenhouse Container, Recycler, and USI Recycler - and moved tech tree nodes around a bit to balance against others.
Added the Air Scrubber and a USI-LS config to the Water Purifier Container - the first is an early-tech low-quality recycler, the second is a small purifier.  Both use already existing (and unused under USI-LS) models and textures.

### CODE REVIEW

**Comment by Nils277** [comment]
Wow, a lot very good changes! Will take a look at them in the next days and merge them.
Next update will be when 1.3 of KSP comes out..

**Comment by DanStaal** [comment]
Thanks.  I want to make sure to acknowledge Merkov for much of it: He did a lot of the legwork on this.

The biggest player-impacting changes are really twofold: First that there are no longer parts that both hold Kerbals and recycle - your basic recycling they'll want a recycler.  Of which there are three.  ;)

And secondly that the Central Hub has been re-thought to be a powerful piece for a large base - but not a powerful piece on it's own.  If you have a large base you want it as a part of that base, but you no longer want to *start* the base with it.

The Air Scrubber part's config could be combined with the Carbon Extractor if you wanted - it's the same model and basically the same stats and intention.  But it was easier for us to work with it as a separate part, and the name and description are both different.

I added support for Soylent under USI-LS, but not for Soylent under TAC-LS, which the Soylent mod supports.  Two main reasons: Firstly, I added it without adding a part because of a feature of USI-Tools which USI-LS depends on, while it would necessarily need to add or replace a part under TAC-LS.  Secondly, I wasn't sure if it could be done with *just* the one part under TAC-LS, as I don't know TAC-LS very well.

**Comment by DanStaal** [comment]
Quick note: RoverDude updated the guidelines for EC costs for habitation - down by a factor of ten.  I made the changes in the patch.

**Comment by Nils277** [comment]
Thanks!

**Pull request merged**
